"""Extras route handlers for NetBox custom field management."""

from typing import Annotated

from fastapi import APIRouter, Depends

from proxbox_api.exception import ProxboxException
from proxbox_api.logger import logger
from proxbox_api.netbox_rest import rest_reconcile_async
from proxbox_api.proxmox_to_netbox.models import NetBoxCustomFieldSyncState
from proxbox_api.session.netbox import NetBoxAsyncSessionDep

router = APIRouter()


@router.get(
    "/extras/custom-fields/create",
    response_model=list[dict],
    response_model_exclude_none=True,
    response_model_exclude_unset=True,
)
async def create_custom_fields(
    netbox_session: NetBoxAsyncSessionDep,
) -> list[dict]:
    """Create custom fields in NetBox for Proxmox synchronization."""
    custom_fields: list = [
        {
            "object_types": ["virtualization.virtualmachine"],
            "type": "integer",
            "name": "proxmox_vm_id",
            "label": "VM ID",
            "description": "Proxmox Virtual Machine or Container ID",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["virtualization.virtualmachine"],
            "type": "text",
            "name": "proxmox_vm_type",
            "label": "VM Type",
            "description": "Proxmox VM type (qemu or lxc)",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["virtualization.virtualmachine"],
            "type": "boolean",
            "name": "proxmox_start_at_boot",
            "label": "Start at Boot",
            "description": "Proxmox Start at Boot Option",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["virtualization.virtualmachine"],
            "type": "boolean",
            "name": "proxmox_unprivileged_container",
            "label": "Unprivileged Container",
            "description": "Proxmox Unprivileged Container",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["virtualization.virtualmachine"],
            "type": "boolean",
            "name": "proxmox_qemu_agent",
            "label": "QEMU Guest Agent",
            "description": "Proxmox QEMU Guest Agent",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["virtualization.virtualmachine"],
            "type": "text",
            "name": "proxmox_search_domain",
            "label": "Search Domain",
            "description": "Proxmox Search Domain",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "url",
            "name": "proxmox_link",
            "label": "Proxmox Link",
            "description": "Link to Proxmox web interface",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_node",
            "label": "Proxmox Node",
            "description": "Proxmox node hosting this device/VM",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_cluster",
            "label": "Proxmox Cluster",
            "description": "Proxmox cluster name",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["virtualization.virtualmachine"],
            "type": "text",
            "name": "proxmox_status",
            "label": "Proxmox Status",
            "description": "Current status in Proxmox",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["virtualization.virtualmachine"],
            "type": "integer",
            "name": "proxmox_uptime",
            "label": "Uptime (seconds)",
            "description": "VM uptime in seconds",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_tags",
            "label": "Proxmox Tags",
            "description": "Comma-separated tags from Proxmox",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_os",
            "label": "Operating System",
            "description": "Operating system from Proxmox",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["virtualization.virtualmachine"],
            "type": "integer",
            "name": "proxmox_cpu",
            "label": "CPU(s)",
            "description": "Number of CPUs",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["virtualization.virtualmachine"],
            "type": "integer",
            "name": "proxmox_memory",
            "label": "Memory (MB)",
            "description": "Memory in MB",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_storage",
            "label": "Storage",
            "description": "Storage disk size",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_disk",
            "label": "Disk (GB)",
            "description": "Total disk size in GB",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_interfaces",
            "label": "Network Interfaces",
            "description": "Network interface count",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["ipam.ipaddress"],
            "type": "text",
            "name": "proxmox_interface",
            "label": "Proxmox Interface",
            "description": "Proxmox network interface name",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_vmid",
            "label": "Proxmox VMID",
            "description": "VM ID for reference",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["ipam.ipaddress"],
            "type": "text",
            "name": "proxmox_mac",
            "label": "Proxmox MAC",
            "description": "MAC address from Proxmox",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_notes",
            "label": "Proxmox Notes",
            "description": "Notes from Proxmox",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["ipam.vlan"],
            "type": "integer",
            "name": "proxmox_vlan_id",
            "label": "Proxmox VLAN ID",
            "description": "VLAN ID from Proxmox",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "virtualization.cluster",
                "virtualization.clustergroup",
            ],
            "type": "text",
            "name": "proxmox_cluster_name",
            "label": "Cluster Name",
            "description": "Cluster name from Proxmox",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "virtualization.cluster",
                "virtualization.clustergroup",
            ],
            "type": "text",
            "name": "proxmox_cluster_status",
            "label": "Cluster Status",
            "description": "Cluster status from Proxmox",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmix_tcp_states",
            "label": "TCP States",
            "description": "TCP connection states",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_cpu_type",
            "label": "CPU Type",
            "description": "CPU type from Proxmox",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["ipam.ipaddress"],
            "type": "text",
            "name": "proxmox_ip_addresses",
            "label": "IP Addresses",
            "description": "All IP addresses from Proxmox",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "virtualization.cluster",
            ],
            "type": "integer",
            "name": "proxmox_cluster_id",
            "label": "Cluster ID",
            "description": "Proxmox cluster ID",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_storage_ids",
            "label": "Storage IDs",
            "description": "Comma-separated storage IDs",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_storage_names",
            "label": "Storage Names",
            "description": "Comma-separated storage names",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.device",
                "virtualization.virtualmachine",
            ],
            "type": "text",
            "name": "proxmox_device_names",
            "label": "Device Names",
            "description": "Comma-separated device names",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["virtualization.vmmigration"],
            "type": "integer",
            "name": "proxmox_migration_duration",
            "label": "Migration Duration",
            "description": "Migration duration in seconds",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": ["virtualization.vmmigration"],
            "type": "text",
            "name": "proxmox_migration_type",
            "label": "Migration Type",
            "description": "Migration type (live / offline)",
            "ui_visible": "if-set",
            "ui_editable": "hidden",
            "weight": 100,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
        {
            "object_types": [
                "dcim.devicerole",
                "dcim.manufacturer",
                "dcim.site",
                "virtualization.vminterface",
                "ipam.ipaddress",
                "virtualization.virtualdisk",
            ],
            "type": "datetime",
            "name": "proxmox_last_updated",
            "label": "Last Updated",
            "description": "Proxmox Plugin last modified this object",
            "ui_visible": "always",
            "ui_editable": "hidden",
            "weight": 200,
            "filter_logic": "loose",
            "search_weight": 1000,
            "group_name": "Proxmox",
        },
    ]
    fields = []

    for custom_field in custom_fields:
        try:
            record = await rest_reconcile_async(
                netbox_session,
                "/api/extras/custom-fields/",
                lookup={"name": custom_field["name"]},
                payload=custom_field,
                schema=NetBoxCustomFieldSyncState,
                current_normalizer=lambda record: {
                    "name": record.get("name"),
                    "type": record.get("type"),
                    "label": record.get("label"),
                    "description": record.get("description"),
                    "ui_visible": record.get("ui_visible"),
                    "ui_editable": record.get("ui_editable"),
                    "weight": record.get("weight"),
                    "filter_logic": record.get("filter_logic"),
                    "search_weight": record.get("search_weight"),
                    "group_name": record.get("group_name"),
                    "object_types": record.get("object_types"),
                },
            )
            fields.append(record.serialize())
        except ProxboxException as e:
            logger.warning(
                "Failed to create/update custom field '%s': %s - %s",
                custom_field.get("name", "unknown"),
                e.message,
                e.detail,
            )
        except Exception as e:
            logger.warning(
                "Failed to create/update custom field '%s': %s",
                custom_field.get("name", "unknown"),
                str(e),
            )
    return fields


CreateCustomFieldsDep = Annotated[list[dict], Depends(create_custom_fields)]
