"""Test factory for :class:`proxbox_api.services.run_session.SyncContext`.

Keeping a single factory means tests pick up new fields automatically
and we don't have to update every call site when the shape grows.
``operation_id`` is required (no silent autogenerated UUID) so
cross-test isolation stays explicit. The forward-compat ``run_uuid`` and
``netbox_branch`` pass through unchanged; Phase A tests do not set
them.
"""

from __future__ import annotations

from proxbox_api.schemas import PluginConfig
from proxbox_api.schemas.netbox import NetboxSessionSchema
from proxbox_api.services.run_session import SyncContext


def make_settings(
    *,
    domain: str = "netbox.example.com",
    http_port: int = 8000,
    token: str = "test-token",
) -> PluginConfig:
    """Build a minimal :class:`PluginConfig` for tests.

    Reconcilers that don't read from ``ctx.settings`` (most of Phase A)
    only need *some* valid instance; the field values don't matter.
    """
    return PluginConfig(
        proxmox=[],
        netbox=NetboxSessionSchema(domain=domain, http_port=http_port, token=token),
    )


def make_session(
    *,
    nb: object,
    px_sessions: list[object],
    tag: object,
    settings: PluginConfig,
    operation_id: str,
    run_uuid: str | None = None,
    netbox_branch: str = "",
) -> SyncContext:
    """Build a :class:`SyncContext` for tests with required positional kwargs.

    Args:
        nb: NetBox async session stand-in.
        px_sessions: List of Proxmox session stand-ins.
        tag: Tag object stand-in.
        settings: Plugin configuration snapshot.
        operation_id: Per-run identifier (required; pass an explicit
            UUID or sentinel to keep cross-test isolation visible).
        run_uuid: Phase B (#367) field. Not set by Phase A tests.
        netbox_branch: Phase C (#370) field. Not set by Phase A tests.

    Returns:
        Frozen :class:`SyncContext` instance.
    """
    return SyncContext(
        nb=nb,
        px_sessions=px_sessions,
        tag=tag,
        settings=settings,
        operation_id=operation_id,
        run_uuid=run_uuid,
        netbox_branch=netbox_branch,
    )
